name: Update SDK and NuGet Packages

on:
  workflow_dispatch:
jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: ./global.json
    - name: Get app token
      uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: ${{ secrets.PULL_REQUEST_APP_ID }}
        private-key: ${{ secrets.PULL_REQUEST_PRIVATE_KEY }}
    - name: Create artifacts/results directory
      run: mkdir -p artifacts/results
    - name: Restore tools
      run: dotnet tool restore
      env:
        NuGetPackageSourceCredentials_apicentric: Username=${{ github.actor }};Password=${{ secrets.GITHUB_TOKEN }}
    - name: Bump NuGet packages
      run: |
        dotnet dotnet-outdated -vl Major -u -o ./artifacts/results/bump-nuget-result.json
      env:
        NuGetPackageSourceCredentials_apicentric: Username=${{ github.actor }};Password=${{ secrets.GITHUB_TOKEN }}
    - name: Bump SDK
      run: |
        dotnet dotbump sdk -o ./artifacts/results/bump-sdk-result.json
    - name: Create pull request
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ steps.app-token.outputs.token }}
        commit-message: "dep: update .NET SDK and NuGet packages"
        title: "dep: update .NET SDK and NuGet packages"
        body: |
          Bump the .NET SDK version and update the NuGet packages.
        branch: bot/dependency-upgrade
        delete-branch: 'true'
        assignees: robyvandamme
    - name: 'Save results'
      uses: actions/upload-artifact@v4
      with:
        name: results
        path: artifacts/results
